version: "3.7"

services:
  influxdb:
    image: influxdb:1.8.3
    container_name: influxdb
    restart: always
    ports:
      - "8086:8086"
    networks:
      - monitor_network
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=dias_kuksa_tut
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  connector:
    image: mrki102/hono-influxdb-connector
    container_name: hono-influxdb-connector
    command: --hono.client.tlsEnabled=true --hono.client.username=messaging@t20babfe7fb2840119f69e692f184127d --hono.client.password=s9VrzSsOQMzlSKFDgHrj --tenant.id=t20babfe7fb2840119f69e692f184127d --export.ip=influxdb:8086
    restart: always
    ports:
      - "8080:8080"
    networks:
      - monitor_network
    depends_on:
      - influxdb
    volumes:
      - connector-storage:/var/lib/connector

  grafana:
    image: grafana/grafana:6.0.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    networks:
      - monitor_network
    depends_on:
      - influxdb
    environment:
      - GF_INSTALL_PLUGINS=natel-plotly-panel # to add plugins
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning/

networks:
  monitor_network:

volumes:
  influxdb-storage:
  connector-storage:
  grafana-storage:
